'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _112_RefreshArrow_Green_16x16_72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_112_RefreshArrow_Green_16x16_72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3threecolumns_9714() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3threecolumns_9714", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property complex1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("complex1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DDPHelp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DDPHelp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Front window is not a mapper..
        '''</summary>
        Friend ReadOnly Property ERR_FRONT_WIN_NOT_MAPPER() As String
            Get
                Return ResourceManager.GetString("ERR_FRONT_WIN_NOT_MAPPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid XML.
        '''</summary>
        Friend ReadOnly Property ERR_INVALID_XML() As String
            Get
                Return ResourceManager.GetString("ERR_INVALID_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to display the dialog..
        '''</summary>
        Friend ReadOnly Property ERR_MB_DLG_NOT_DISPLAYED() As String
            Get
                Return ResourceManager.GetString("ERR_MB_DLG_NOT_DISPLAYED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GotoFirstRow_287() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GotoFirstRow_287", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GotoLastRow_288() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GotoLastRow_288", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GotoNextRow_289() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GotoNextRow_289", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GotoNextRow_289Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GotoNextRow_289Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MapInfow_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MapInfow_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavigateBackwards_6270() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigateBackwards_6270", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavigateForward_6271() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigateForward_6271", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Open_6529() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Open_6529", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save_6530() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save_6530", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About {0}.
        '''</summary>
        Friend ReadOnly Property STR_ABOUT() As String
            Get
                Return ResourceManager.GetString("STR_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -.
        '''</summary>
        Friend ReadOnly Property STR_ABT_DESC1() As String
            Get
                Return ResourceManager.GetString("STR_ABT_DESC1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -.
        '''</summary>
        Friend ReadOnly Property STR_ABT_DESC2() As String
            Get
                Return ResourceManager.GetString("STR_ABT_DESC2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Folder.
        '''</summary>
        Friend ReadOnly Property STR_DEF_FOLDER_NAME() As String
            Get
                Return ResourceManager.GetString("STR_DEF_FOLDER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MapInfoDataDrivenPages.
        '''</summary>
        Friend ReadOnly Property STR_MB_APP_DESC() As String
            Get
                Return ResourceManager.GetString("STR_MB_APP_DESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MapInfoDataDrivenPages.MBX.
        '''</summary>
        Friend ReadOnly Property STR_MB_APP_FILENAME() As String
            Get
                Return ResourceManager.GetString("STR_MB_APP_FILENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MapInfoDataDrivenPages.
        '''</summary>
        Friend ReadOnly Property STR_MB_BTN_PAD_HLPMSG() As String
            Get
                Return ResourceManager.GetString("STR_MB_BTN_PAD_HLPMSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools.
        '''</summary>
        Friend ReadOnly Property STR_MB_BTN_PAD_TOOLS() As String
            Get
                Return ResourceManager.GetString("STR_MB_BTN_PAD_TOOLS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;About MapInfoDataDrivenPages....
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_ABOUT() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;xit MapInfoDataDrivenPages.
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_EXIT() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;MapInfoDataDrivenPages.
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_PROFILETOOL() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_PROFILETOOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;MapInfoDataDrivenPages.
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_SUBTITLE() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_SUBTITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Center = ({0}, {1}) - Zoom = {2} {3}.
        '''</summary>
        Friend ReadOnly Property STR_TOOLTIP_VIEW() As String
            Get
                Return ResourceManager.GetString("STR_TOOLTIP_VIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0}.
        '''</summary>
        Friend ReadOnly Property STR_VERSION() As String
            Get
                Return ResourceManager.GetString("STR_VERSION", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
